### ISSUE TITLE
建议降低食谱tag选择页面透明度

### ISSUE THREAD

**Issue by ghost** [Troublemove/touhou-izakaya-helper#1]
![IMG_20240604_163351.jpg](https://github.com/Troublemove/touhou-izakaya-helper/assets/74867256/d4211e3c-6e57-4be6-8450-79a50a47614d)

![Screenshot_2024-06-04-16-34-42-846_com.android.settings.jpg](https://github.com/Troublemove/touhou-izakaya-helper/assets/74867256/c251c24c-8bdc-4342-b507-b4e9eefdc9ac)

现在这样看上去比较乱，并且还有一条白色的线

**Comment by Troublemove** [comment]
透明度主要是想选择tag后，能直接看到下面料理的变化，透明度目前是0.5，之后可以提高些。
下面的白线忘记去掉了，之后可以去掉。
乱主要是因为排版不行吧，我没做什么设计。
