### ISSUE TITLE
酒水页面三个字的 tag 会换行

### ISSUE THREAD

**Issue by ghost** [Troublemove/touhou-izakaya-helper#2]
v1.1.2版本

![Screenshot_2024-06-05-19-45-16-443_com.touhou.helper.jpg](https://github.com/Troublemove/touhou-izakaya-helper/assets/74867256/d801e32f-b63a-4b49-9bf7-4b18a18c3800)

**Comment by ghost** [comment]
可能是因为tag前加了 "·"？

**Comment by Troublemove** [comment]
我手机没有这个现象，下个版本把这个统一一下，把前面·去了。
